export const types = {
  CHANGE_TITLE: "CHANGE_TITLE",
  WITH_PARAMS: "WITH_PARAMS",
  FROM_INPUT: "FROM_INPUT",
  ADD_TASK: "ADD_TASK",
  TOGGLE_TASK: "TOOGLE_TASK",
  CHANGE: "CHANGE",
  DELETE: "DELETE",
};
